/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DevotionalVoicePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/constants.ts
var MODELS = {
  openai: "whisper-1",
  groq: "whisper-large-v3"
};
var API_ENDPOINTS = {
  openai: "https://api.openai.com/v1/audio/transcriptions",
  groq: "https://api.groq.com/openai/v1/audio/transcriptions"
};
var API_TEST_ENDPOINTS = {
  openai: "https://api.openai.com/v1/models",
  groq: "https://api.groq.com/openai/v1/models"
};
var API_CONFIG = {
  TIMEOUT_MS: 3e5,
  // 5 minutes (increased for long recordings)
  MAX_FILE_SIZE_MB: 25,
  AUDIO_MIME_TYPE: "audio/webm"
};
var ERROR_MESSAGES = {
  API_KEY_MISSING: "API Key is missing. Please set it in settings.",
  API_KEY_INVALID_FORMAT: (provider) => `Invalid API key format for ${provider}. Please check your API key.`,
  TRANSCRIPTION_FAILED: "Transcription failed. Check console for details.",
  TRANSCRIPTION_TIMEOUT: "Transcription timed out. Please try again.",
  MICROPHONE_PERMISSION_DENIED: "Microphone access denied. Please allow microphone access in your browser/system settings.",
  MICROPHONE_NOT_FOUND: "No microphone found. Please connect a microphone and try again.",
  MICROPHONE_GENERAL_ERROR: "Failed to access microphone. Please check your audio settings.",
  NO_ACTIVE_RECORDING: "No active recording to stop.",
  API_UNAUTHORIZED: "Incorrect API Key (401). Please check your settings.",
  API_QUOTA_EXCEEDED: "API Quota Exceeded (429). Please check your plan."
};
var SUCCESS_MESSAGES = {
  RECORDING_STARTED: "Recording started...",
  TRANSCRIPTION_COMPLETE: "Transcription complete!",
  SETTINGS_SAVED: (service, lang) => `Settings saved: ${service} / ${lang}`,
  QUICK_SETTINGS_SAVED: (service, lang, diarization) => `Settings: ${service} / ${lang}${diarization ? " / Speaker Diarization ON" : ""}`,
  COPIED_TO_CLIPBOARD: "Text copied to clipboard (No active editor)",
  API_KEY_VALID: "API key is valid!",
  API_KEY_TEST_START: "Testing API key..."
};
var API_TEST_ERRORS = {
  INVALID_KEY: "Invalid API Key. Please check and try again.",
  QUOTA_EXCEEDED: "API Quota exceeded. Check your billing.",
  NETWORK_ERROR: "Network error. Check your internet connection.",
  UNKNOWN_ERROR: "Test failed. Check console for details."
};

// src/recorder.ts
var MicrophoneRecorder = class {
  constructor() {
    this.mediaRecorder = null;
    this.audioChunks = [];
  }
  async startRecording() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      this.mediaRecorder = new MediaRecorder(stream);
      this.audioChunks = [];
      this.mediaRecorder.addEventListener("dataavailable", (event) => {
        this.audioChunks.push(event.data);
      });
      this.mediaRecorder.start();
    } catch (error) {
      console.error("Error starting recording:", error);
      throw this.parseMediaError(error);
    }
  }
  async stopRecording() {
    return new Promise((resolve, reject) => {
      if (!this.mediaRecorder) {
        reject(new Error(ERROR_MESSAGES.NO_ACTIVE_RECORDING));
        return;
      }
      this.mediaRecorder.addEventListener("stop", () => {
        var _a;
        const audioBlob = new Blob(this.audioChunks, { type: "audio/webm" });
        this.audioChunks = [];
        (_a = this.mediaRecorder) == null ? void 0 : _a.stream.getTracks().forEach((track) => track.stop());
        this.mediaRecorder = null;
        resolve(audioBlob);
      });
      this.mediaRecorder.stop();
    });
  }
  isRecording() {
    var _a;
    return ((_a = this.mediaRecorder) == null ? void 0 : _a.state) === "recording";
  }
  getStream() {
    var _a;
    return ((_a = this.mediaRecorder) == null ? void 0 : _a.stream) || null;
  }
  /**
   * Parse media device errors and provide user-friendly messages
   */
  parseMediaError(error) {
    if (error instanceof DOMException) {
      switch (error.name) {
        case "NotAllowedError":
        case "PermissionDeniedError":
          return {
            type: "permission_denied",
            message: ERROR_MESSAGES.MICROPHONE_PERMISSION_DENIED,
            originalError: error
          };
        case "NotFoundError":
        case "DevicesNotFoundError":
          return {
            type: "not_found",
            message: ERROR_MESSAGES.MICROPHONE_NOT_FOUND,
            originalError: error
          };
        default:
          return {
            type: "general",
            message: ERROR_MESSAGES.MICROPHONE_GENERAL_ERROR,
            originalError: error
          };
      }
    }
    return {
      type: "general",
      message: ERROR_MESSAGES.MICROPHONE_GENERAL_ERROR,
      originalError: error instanceof Error ? error : new Error(String(error))
    };
  }
};

// src/transcription.ts
var import_obsidian = require("obsidian");
var TranscriptionService = class {
  /**
   * Test API key validity by calling the models endpoint
   */
  async testApiKey(apiKey, serviceProvider) {
    var _a, _b;
    if (!apiKey || apiKey.trim().length === 0) {
      return {
        success: false,
        message: API_TEST_ERRORS.INVALID_KEY,
        details: "API key is empty"
      };
    }
    const url = API_TEST_ENDPOINTS[serviceProvider];
    const params = {
      url,
      method: "GET",
      headers: {
        "Authorization": `Bearer ${apiKey.trim()}`
      },
      throw: false
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(params);
      console.log(`API Test Response (${serviceProvider}):`, {
        status: response.status,
        data: response.json
      });
      if (response.status === 200) {
        return {
          success: true,
          message: SUCCESS_MESSAGES.API_KEY_VALID,
          details: `Connected to ${serviceProvider.toUpperCase()} API successfully`
        };
      } else if (response.status === 401) {
        return {
          success: false,
          message: API_TEST_ERRORS.INVALID_KEY,
          details: ((_b = (_a = response.json) == null ? void 0 : _a.error) == null ? void 0 : _b.message) || "Authentication failed"
        };
      } else if (response.status === 429) {
        return {
          success: false,
          message: API_TEST_ERRORS.QUOTA_EXCEEDED,
          details: "Rate limit or quota exceeded"
        };
      } else {
        return {
          success: false,
          message: API_TEST_ERRORS.UNKNOWN_ERROR,
          details: `HTTP ${response.status}: ${JSON.stringify(response.json)}`
        };
      }
    } catch (error) {
      console.error("API Test Error:", error);
      return {
        success: false,
        message: API_TEST_ERRORS.NETWORK_ERROR,
        details: error instanceof Error ? error.message : "Unknown error"
      };
    }
  }
  async transcribe(audioBlob, apiKey, language, serviceProvider, fileName, mimeType) {
    if (!apiKey) {
      new import_obsidian.Notice(ERROR_MESSAGES.API_KEY_MISSING);
      throw new Error("API Key missing");
    }
    if (!this.isValidApiKeyFormat(apiKey, serviceProvider)) {
      new import_obsidian.Notice(ERROR_MESSAGES.API_KEY_INVALID_FORMAT(serviceProvider));
      throw new Error("Invalid API key format");
    }
    const arrayBuffer = await audioBlob.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const actualFileName = fileName || "recording.webm";
    const actualMimeType = mimeType || audioBlob.type || API_CONFIG.AUDIO_MIME_TYPE;
    const boundary = "----ObsidianVoiceWritingBoundary" + Date.now();
    const body = await this.createFormData(buffer, actualFileName, actualMimeType, boundary, language, serviceProvider);
    const url = API_ENDPOINTS[serviceProvider];
    const params = {
      url,
      method: "POST",
      headers: {
        "Content-Type": `multipart/form-data; boundary=${boundary}`,
        "Authorization": `Bearer ${apiKey}`
      },
      body,
      throw: false
      // Don't throw on non-2xx responses
    };
    try {
      const timeoutPromise = new Promise((_, reject) => {
        setTimeout(() => {
          reject(new Error("TIMEOUT"));
        }, API_CONFIG.TIMEOUT_MS);
      });
      const response = await Promise.race([
        (0, import_obsidian.requestUrl)(params),
        timeoutPromise
      ]);
      if (response.status !== 200) {
        console.error("Transcription failed:", response.json);
        if (response.status === 401) {
          throw new Error("API_UNAUTHORIZED");
        }
        if (response.status === 429) {
          throw new Error("API_QUOTA_EXCEEDED");
        }
        throw new Error(`Transcription failed: ${response.status}`);
      }
      return { text: response.json.text };
    } catch (error) {
      if (error instanceof Error && error.message === "TIMEOUT") {
        console.error("Transcription timeout after", API_CONFIG.TIMEOUT_MS, "ms");
        new import_obsidian.Notice(ERROR_MESSAGES.TRANSCRIPTION_TIMEOUT);
        throw new Error("Transcription timeout");
      }
      console.error("Transcription error:", error);
      new import_obsidian.Notice(ERROR_MESSAGES.TRANSCRIPTION_FAILED);
      throw error;
    }
  }
  isValidApiKeyFormat(apiKey, provider) {
    const trimmedKey = apiKey.trim();
    if (provider === "openai") {
      return trimmedKey.startsWith("sk-") && trimmedKey.length > 20;
    } else if (provider === "groq") {
      return trimmedKey.length > 20 && !/\s/.test(trimmedKey);
    }
    return trimmedKey.length > 10;
  }
  parseErrorResponse(response) {
    var _a;
    try {
      const json = response.json;
      if ((_a = json == null ? void 0 : json.error) == null ? void 0 : _a.message) {
        return {
          status: response.status,
          message: json.error.message,
          details: json.error.type || json.error.code
        };
      }
      return {
        status: response.status,
        message: `HTTP ${response.status} Error`,
        details: JSON.stringify(json)
      };
    } catch (e) {
      return {
        status: response.status,
        message: `HTTP ${response.status} Error`,
        details: "Could not parse error response"
      };
    }
  }
  async createFormData(fileBuffer, fileName, mimeType, boundary, language, provider) {
    const parts = [];
    const model = MODELS[provider];
    parts.push(Buffer.from(`--${boundary}\r
`));
    parts.push(Buffer.from(`Content-Disposition: form-data; name="file"; filename="${fileName}"\r
`));
    parts.push(Buffer.from(`Content-Type: ${mimeType}\r
\r
`));
    parts.push(fileBuffer);
    parts.push(Buffer.from(`\r
`));
    parts.push(Buffer.from(`--${boundary}\r
`));
    parts.push(Buffer.from(`Content-Disposition: form-data; name="model"\r
\r
`));
    parts.push(Buffer.from(`${model}\r
`));
    if (language && language !== "auto") {
      parts.push(Buffer.from(`--${boundary}\r
`));
      parts.push(Buffer.from(`Content-Disposition: form-data; name="language"\r
\r
`));
      parts.push(Buffer.from(`${language}\r
`));
    }
    parts.push(Buffer.from(`--${boundary}--\r
`));
    return Buffer.concat(parts).buffer;
  }
};

// src/rag.ts
var import_obsidian2 = require("obsidian");
var RAGService = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * Search for relevant notes based on the input text
   */
  async search(query, topK = 5) {
    const results = [];
    const vault = this.app.vault;
    const files = vault.getMarkdownFiles().filter(
      (file) => this.isInWhitelistFolder(file.path)
    );
    let keywords = this.extractKeywords(query);
    if (this.settings.geminiApiKey && keywords.length > 0) {
      try {
        const expandedKeywords = await this.expandKeywordsWithLLM(query);
        if (expandedKeywords.length > 0) {
          console.log("[RAG] Expanded Keywords:", expandedKeywords);
          keywords = [.../* @__PURE__ */ new Set([...keywords, ...expandedKeywords])];
        }
      } catch (e) {
        console.error("[RAG] Expansion failed, falling back to basic search:", e);
      }
    }
    for (const file of files) {
      const content = await vault.cachedRead(file);
      const score = this.calculateRelevanceScore(content, keywords);
      if (score > 0) {
        results.push({
          file,
          score,
          excerpt: this.extractExcerpt(content, keywords)
        });
      }
    }
    return results.sort((a, b) => b.score - a.score).slice(0, topK);
  }
  /**
   * Check if a file path is in the whitelist folders
   */
  isInWhitelistFolder(filePath) {
    if (this.settings.whitelistFolders.length === 0) {
      return true;
    }
    return this.settings.whitelistFolders.some(
      (folder) => filePath.startsWith(folder.trim())
    );
  }
  /**
   * Extract keywords from the query text
   */
  extractKeywords(text) {
    const stopwords = ["\uC740", "\uB294", "\uC774", "\uAC00", "\uC744", "\uB97C", "\uC5D0", "\uC758", "\uC640", "\uACFC", "\uB85C", "\uC73C\uB85C", "\uC5D0\uC11C", "\uD558\uB2E4", "\uB418\uB2E4", "\uC788\uB2E4", "\uC5C6\uB2E4"];
    const words = text.split(/[\s,.!?;:'"()[\]{}]+/).filter((word) => word.length > 1).filter((word) => !stopwords.includes(word)).map((word) => word.toLowerCase());
    return [...new Set(words)];
  }
  /**
   * Calculate relevance score based on keyword matching
   */
  calculateRelevanceScore(content, keywords) {
    const lowerContent = content.toLowerCase();
    let score = 0;
    for (const keyword of keywords) {
      const escapedKeyword = this.escapeRegExp(keyword);
      try {
        const regex = new RegExp(escapedKeyword, "gi");
        const matches = lowerContent.match(regex);
        if (matches) {
          score += matches.length;
        }
      } catch (e) {
        console.warn(`[RAG] Skipping invalid keyword: ${keyword}`);
      }
    }
    return score;
  }
  /**
   * Escape special characters for use in RegExp
   */
  escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  /**
   * Extract relevant excerpt from content
   */
  extractExcerpt(content, keywords, maxLength = 300) {
    const lowerContent = content.toLowerCase();
    for (const keyword of keywords) {
      const index = lowerContent.indexOf(keyword.toLowerCase());
      if (index !== -1) {
        const start = Math.max(0, index - 50);
        const end = Math.min(content.length, index + maxLength);
        return "..." + content.slice(start, end).trim() + "...";
      }
    }
    return content.slice(0, maxLength).trim() + "...";
  }
  /**
   * Update settings
   */
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Expand query using LLM to find theological synonyms and related concepts
   */
  async expandKeywordsWithLLM(query) {
    var _a, _b, _c, _d, _e, _f;
    const model = this.settings.geminiModel || "gemini-2.0-flash";
    const apiKey = this.settings.geminiApiKey;
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const prompt = `Analyze this devotional text and extract 5-8 related theological conceptual keywords (synonyms, biblical themes, key terms).
        Text: "${query.substring(0, 500)}"
        
        Output only a comma-separated list of keywords. No explanations.
        Example: Grace, Salvation, Cross, Redemption`;
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: apiUrl,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.3 }
        })
      });
      if (response.status !== 200)
        return [];
      const text = (_f = (_e = (_d = (_c = (_b = (_a = response.json) == null ? void 0 : _a.candidates) == null ? void 0 : _b[0]) == null ? void 0 : _c.content) == null ? void 0 : _d.parts) == null ? void 0 : _e[0]) == null ? void 0 : _f.text;
      if (!text)
        return [];
      return text.split(",").map((k) => k.trim()).filter((k) => k.length > 0);
    } catch (e) {
      console.error("[RAG] LLM Expansion Error:", e);
      return [];
    }
  }
};

// src/generation.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_TEMPLATE = `\uB2F9\uC2E0\uC740 \uD0C1\uC6D4\uD55C \uC601\uC131\uC744 \uC9C0\uB2CC \uC2E0\uD559\uC790\uC774\uC790, \uCCAD\uC911\uC758 \uB9C8\uC74C\uC744 \uC704\uB85C\uD558\uB294 \uC124\uAD50\uC790\uC785\uB2C8\uB2E4.

\uC0AC\uC6A9\uC790\uC758 \uBB35\uC0C1 \uB0B4\uC6A9\uACFC \uAD00\uB828 \uB178\uD2B8\uB97C \uBC14\uD0D5\uC73C\uB85C, \uAE4A\uC774 \uC788\uB294 \uC2E0\uD559\uC801 \uD1B5\uCC30\uACFC \uB530\uB73B\uD55C \uBAA9\uD68C\uC801 \uC801\uC6A9\uC774 \uB2F4\uAE34 \uBB35\uC0C1\uAE00\uC744 \uC791\uC131\uD574 \uC8FC\uC138\uC694.

## \uCD9C\uB825 \uD615\uC2DD (\uC808\uB300 \uC900\uC218)
1. \uBA3C\uC800 **\uBB35\uC0C1\uAE00 \uBCF8\uBB38(Markdown)**\uC744 \uC791\uC131\uD558\uC138\uC694.
2. \uBCF8\uBB38\uC774 \uB05D\uB098\uBA74 \uBC18\uB4DC\uC2DC **\`|||TTS_SCRIPT_START|||\`** \uB77C\uB294 \uAD6C\uBD84\uC790\uB97C \uD55C \uC904\uC5D0 \uC791\uC131\uD558\uC138\uC694. (JSON \uD615\uD0DC\uB098 \`\`\`json \uCF54\uB4DC \uBE14\uB85D\uC744 \uC808\uB300 \uC0AC\uC6A9\uD558\uC9C0 \uB9C8\uC138\uC694. \uC624\uC9C1 \uC77C\uBC18 \uBB38\uC7A5\uACFC \uAD6C\uBD84\uC790\uB9CC \uC0AC\uC6A9\uD558\uC138\uC694.)
3. \uADF8 \uB4A4\uC5D0 **TTS \uB300\uBCF8**\uC744 \uC791\uC131\uD558\uC138\uC694.

## \uC791\uC131 \uC9C0\uCE68
1. **Markdown \uBCF8\uBB38**:
   - \uC2E0\uD559\uC801 \uAE4A\uC774\uAC00 \uC788\uC5B4\uC57C \uD558\uBA70, \uBCF8\uBB38\uC758 \uB9E5\uB77D\uC744 \uC815\uD655\uD788 \uC9DA\uC5B4\uC57C \uD568.
   - \uC801\uC6A9\uC740 \uB9C9\uC5F0\uD558\uC9C0 \uC54A\uACE0 \uAD6C\uCCB4\uC801\uC774\uC5B4\uC57C \uD568.

2. **TTS \uB300\uBCF8**:
   - **\uC5B4\uC870**: \uB77C\uB514\uC624 \uC2EC\uC57C \uBC29\uC1A1 \uC9C4\uD589\uC790\uCC98\uB7FC \uB530\uB73B\uD558\uACE0 \uCC28\uBD84\uD558\uBA70, \uB4E3\uB294 \uC774\uC758 \uAC10\uC815\uC744 \uC5B4\uB8E8\uB9CC\uC9C0\uB294 \uD1A4.
   - **\uC139\uC158 \uAD6C\uBD84**: "\uC624\uB298\uC758 \uBB35\uC0C1 \uBCF8\uBB38\uC785\uB2C8\uB2E4", "\uC7A0\uC2DC \uC6B0\uB9AC \uC0B6\uC744 \uB3CC\uC544\uBD05\uC2DC\uB2E4" \uBA58\uD2B8 \uD3EC\uD568.
   - **\uBB38\uCCB4**: \uBD80\uB4DC\uB7EC\uC6B4 \uAD6C\uC5B4\uCCB4. \uC774\uBAA8\uC9C0 \uC81C\uAC70.

\uC5B8\uC5B4: \uD55C\uAD6D\uC5B4`;
var GenerationService = class {
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * Generate devotional content
   */
  async generate(userInput, ragResults) {
    if (!this.settings.geminiApiKey) {
      throw new Error("Gemini API key is not configured");
    }
    const context = this.buildContext(ragResults);
    const prompt = this.buildPrompt(userInput, context);
    const response = await this.callGemini(prompt);
    console.log("[DevotionalVoice] Gemini raw response:", response.substring(0, 500));
    const result = this.parseResponse(response);
    console.log("[DevotionalVoice] Parsed result:", { markdownLength: result.markdown.length, ttsLength: result.ttsScript.length });
    return result;
  }
  /**
   * Build context from RAG search results
   */
  buildContext(results) {
    if (results.length === 0) {
      return "\uAD00\uB828 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.";
    }
    return results.map(
      (result, index) => `### \uAD00\uB828 \uB178\uD2B8 ${index + 1}: ${result.file.basename}
${result.excerpt}`
    ).join("\n\n");
  }
  /**
   * Build the final prompt
   */
  buildPrompt(userInput, context) {
    const template = this.settings.devotionalTemplate || DEFAULT_TEMPLATE;
    return `${template}

## \uC0AC\uC6A9\uC790 \uBB35\uC0C1 \uB0B4\uC6A9
${userInput}

## \uC0AC\uC6A9\uC790\uC758 \uAE30\uC874 \uB178\uD2B8 (\uCC38\uACE0\uC6A9)
${context}

\uC704 \uB0B4\uC6A9\uC744 \uBC14\uD0D5\uC73C\uB85C \uBB35\uC0C1\uAE00\uACFC TTS \uB300\uBCF8\uC744 \uC791\uC131\uD574 \uC8FC\uC138\uC694. \uAD6C\uBD84\uC790(\`|||TTS_SCRIPT_START|||\`)\uB97C \uC78A\uC9C0 \uB9C8\uC138\uC694.`;
  }
  /**
   * Call Gemini API
   */
  async callGemini(prompt) {
    var _a, _b, _c, _d, _e;
    const model = this.settings.geminiModel || "gemini-2.0-flash";
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.settings.geminiApiKey}`;
    try {
      const response = await (0, import_obsidian3.requestUrl)({
        url: apiUrl,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 8192,
            response_mime_type: "application/json"
          }
        })
      });
      if (response.status !== 200) {
        throw new Error(`Gemini API error: ${response.status}`);
      }
      const data = response.json;
      return ((_e = (_d = (_c = (_b = (_a = data.candidates) == null ? void 0 : _a[0]) == null ? void 0 : _b.content) == null ? void 0 : _c.parts) == null ? void 0 : _d[0]) == null ? void 0 : _e.text) || "{}";
    } catch (error) {
      console.error("Gemini API error:", error);
      throw new Error(`Failed to generate devotional: ${error.message}`);
    }
  }
  parseResponse(response) {
    const separator = "|||TTS_SCRIPT_START|||";
    if (response.includes(separator)) {
      const [markdown, tts] = response.split(separator);
      return {
        markdown: markdown.trim(),
        ttsScript: tts.trim()
      };
    }
    try {
      let cleanedResponse = response.trim();
      const codeBlockMatch = cleanedResponse.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
      if (codeBlockMatch && codeBlockMatch[1]) {
        cleanedResponse = codeBlockMatch[1].trim();
      }
      const parsed = JSON.parse(cleanedResponse);
      return {
        markdown: parsed.markdown || response,
        ttsScript: parsed.ttsScript || ""
      };
    } catch (e) {
      return {
        markdown: response,
        ttsScript: ""
      };
    }
  }
  /**
   * Build prompt for generating ONLY a TTS script
   */
  buildTtsOnlyPrompt(noteContent) {
    return `\uB2F9\uC2E0\uC740 \uD0C1\uC6D4\uD55C \uC601\uC131\uC744 \uC9C0\uB2CC \uC2E0\uD559\uC790\uC774\uC790, \uCCAD\uC911\uC758 \uB9C8\uC74C\uC744 \uC704\uB85C\uD558\uB294 \uC124\uAD50\uC790\uC785\uB2C8\uB2E4.
\uC0AC\uC6A9\uC790\uC758 \uB178\uD2B8 \uB0B4\uC6A9\uC744 \uBC14\uD0D5\uC73C\uB85C, \uC774\uB97C \uB0AD\uB3C5\uD558\uAE30 \uC801\uD569\uD55C '\uB77C\uB514\uC624 \uC2EC\uC57C \uBC29\uC1A1' \uD1A4\uC758 TTS \uB300\uBCF8\uC744 \uC791\uC131\uD574 \uC8FC\uC138\uC694.

## \uC791\uC131 \uC9C0\uCE68
1. **\uC5B4\uC870**: \uB530\uB73B\uD558\uACE0 \uCC28\uBD84\uD558\uBA70, \uB4E3\uB294 \uC774\uC758 \uAC10\uC815\uC744 \uC5B4\uB8E8\uB9CC\uC9C0\uB294 \uD1A4.
2. **\uC139\uC158 \uAD6C\uBD84**: "\uC548\uB155\uD558\uC138\uC694", "\uC624\uB298 \uC6B0\uB9AC\uC5D0\uAC8C \uC8FC\uC2E0 \uB9D0\uC500 \uD639\uC740 \uB098\uB214\uC785\uB2C8\uB2E4" \uB4F1\uC758 \uC624\uD504\uB2DD\uACFC \uD074\uB85C\uC9D5 \uBA58\uD2B8 \uD3EC\uD568.
3. **\uBB38\uCCB4**: \uBD80\uB4DC\uB7EC\uC6B4 \uAD6C\uC5B4\uCCB4. \uC774\uBAA8\uC9C0 \uC81C\uAC70.
4. **\uB0B4\uC6A9**: \uB178\uD2B8\uC758 \uD575\uC2EC \uD1B5\uCC30\uC744 \uD558\uB098\uB3C4 \uBE60\uB728\uB9AC\uC9C0 \uC54A\uACE0 \uC790\uC5F0\uC2A4\uB7FD\uAC8C \uC5F0\uACB0\uD558\uC5EC \uB0AD\uB3C5\uBB38\uC73C\uB85C \uBCC0\uD658.

## \uB178\uD2B8 \uB0B4\uC6A9
${noteContent}

## \uCD9C\uB825 \uD615\uC2DD
\uBCC4\uB3C4\uC758 \uB3C4\uC785\uBD80 \uC5C6\uC774 \uBC14\uB85C TTS \uB300\uBCF8\uB9CC \uC791\uC131\uD574 \uC8FC\uC138\uC694. (\uB9C8\uD06C\uB2E4\uC6B4 \uC81C\uBAA9 \uB4F1\uC740 \uC0DD\uB7B5\uD558\uACE0 \uC2E4\uC81C \uC77D\uC744 \uB0B4\uC6A9\uB9CC \uC791\uC131)`;
  }
  /**
   * Stream generate ONLY TTS Script using Fetch API
   */
  async *streamGenerateTts(noteContent) {
    var _a, _b, _c, _d, _e;
    if (!this.settings.geminiApiKey) {
      throw new Error("Gemini API key is not configured");
    }
    const prompt = this.buildTtsOnlyPrompt(noteContent);
    console.log(`[DevotionalVoice] TTS-Only Prompt built. Length: ${prompt.length} chars`);
    const model = this.settings.geminiModel || "gemini-2.0-flash";
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?key=${this.settings.geminiApiKey}`;
    console.log(`[DevotionalVoice] Calling Gemini Stream API (${model}) for TTS-only...`);
    try {
      const response = await fetch(apiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 8192
          }
        })
      });
      if (!response.ok) {
        throw new Error(`Gemini Stream API error: ${response.status}`);
      }
      if (!response.body)
        throw new Error("No response body");
      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      let accumulatedText = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done)
          break;
        buffer += decoder.decode(value, { stream: true });
        let loopAgain = true;
        while (loopAgain) {
          loopAgain = false;
          const firstBrace = buffer.indexOf("{");
          if (firstBrace === -1) {
            break;
          } else if (firstBrace > 0) {
            buffer = buffer.substring(firstBrace);
          }
          let openBraces = 0;
          let inString = false;
          let escaped = false;
          for (let j = 0; j < buffer.length; j++) {
            const c = buffer[j];
            if (escaped) {
              escaped = false;
              continue;
            }
            if (c === "\\") {
              escaped = true;
              continue;
            }
            if (c === '"') {
              inString = !inString;
              continue;
            }
            if (!inString) {
              if (c === "{")
                openBraces++;
              else if (c === "}") {
                openBraces--;
                if (openBraces === 0) {
                  const rawJson = buffer.substring(0, j + 1);
                  try {
                    const p = JSON.parse(rawJson);
                    const txt = (_e = (_d = (_c = (_b = (_a = p.candidates) == null ? void 0 : _a[0]) == null ? void 0 : _b.content) == null ? void 0 : _c.parts) == null ? void 0 : _d[0]) == null ? void 0 : _e.text;
                    if (txt) {
                      accumulatedText += txt;
                      yield txt;
                    }
                  } catch (e) {
                  }
                  buffer = buffer.substring(j + 1);
                  loopAgain = true;
                  break;
                }
              }
            }
          }
        }
      }
      return accumulatedText;
    } catch (error) {
      console.error("Gemini Stream TTS Error:", error);
      throw error;
    }
  }
  /**
   * Stream generate using Fetch API
   */
  async *streamGenerate(userInput, ragResults) {
    if (!this.settings.geminiApiKey) {
      throw new Error("Gemini API key is not configured");
    }
    const context = this.buildContext(ragResults);
    const prompt = this.buildPrompt(userInput, context);
    console.log(`[DevotionalVoice] Generation Prompt built. Length: ${prompt.length} chars`);
    const model = this.settings.geminiModel || "gemini-2.0-flash";
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?key=${this.settings.geminiApiKey}`;
    console.log(`[DevotionalVoice] Calling Gemini Stream API (${model})...`);
    try {
      const response = await fetch(apiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 8192
          }
        })
      });
      if (!response.ok) {
        throw new Error(`Gemini Stream API error: ${response.status}`);
      }
      if (!response.body)
        throw new Error("No response body");
      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      return yield* this.processBufferWithLogic(reader, decoder);
    } catch (error) {
      console.error("Gemini Stream Error:", error);
      throw error;
    }
  }
  async *processBufferWithLogic(reader, decoder) {
    var _a, _b, _c, _d, _e;
    let buffer = "";
    let accumulatedText = "";
    console.log("[DevotionalVoice] Stream reader obtained. Starting loop...");
    while (true) {
      const { done, value } = await reader.read();
      if (done) {
        console.log("[DevotionalVoice] Stream reading complete.");
        break;
      }
      console.log(`[DevotionalVoice] Received chunk of ${value.length} bytes`);
      buffer += decoder.decode(value, { stream: true });
      let loopAgain = true;
      while (loopAgain) {
        loopAgain = false;
        const firstBrace = buffer.indexOf("{");
        if (firstBrace === -1) {
          if (buffer.length > 200) {
            buffer = buffer.substring(buffer.length - 50);
          }
          break;
        } else if (firstBrace > 0) {
          buffer = buffer.substring(firstBrace);
        }
        let openBraces = 0;
        let inString = false;
        let escaped = false;
        for (let j = 0; j < buffer.length; j++) {
          const c = buffer[j];
          if (escaped) {
            escaped = false;
            continue;
          }
          if (c === "\\") {
            escaped = true;
            continue;
          }
          if (c === '"') {
            inString = !inString;
            continue;
          }
          if (!inString) {
            if (c === "{") {
              openBraces++;
            } else if (c === "}") {
              openBraces--;
              if (openBraces === 0) {
                const rawJson = buffer.substring(0, j + 1);
                try {
                  const p = JSON.parse(rawJson);
                  const txt = (_e = (_d = (_c = (_b = (_a = p.candidates) == null ? void 0 : _a[0]) == null ? void 0 : _b.content) == null ? void 0 : _c.parts) == null ? void 0 : _d[0]) == null ? void 0 : _e.text;
                  if (txt) {
                    accumulatedText += txt;
                    yield txt;
                  }
                } catch (e) {
                  console.error("[DevotionalVoice] JSON Parse Failed:", e);
                }
                buffer = buffer.substring(j + 1);
                loopAgain = true;
                break;
              }
            }
          }
        }
      }
    }
    return this.parseResponse(accumulatedText);
  }
  /**
   * Update settings
   */
  updateSettings(settings) {
    this.settings = settings;
  }
};

// src/tts.ts
var import_obsidian4 = require("obsidian");
var TTSService = class {
  constructor(settings) {
    this.currentAudio = null;
    this.settings = settings;
  }
  async speak(text) {
    this.stop();
    if (this.settings.provider === "google") {
      if ("speechSynthesis" in window) {
        this.speakWithWebSpeech(text);
      } else {
        new import_obsidian4.Notice("TTS not supported");
      }
      return;
    }
    const audioBuffer = await this.generateAudio(text);
    if (audioBuffer) {
      await this.playAudioBuffer(audioBuffer);
    }
  }
  async generateAudio(text) {
    if (this.settings.provider === "openai") {
      return await this.generateOpenAIAudio(text);
    } else if (this.settings.provider === "gemini") {
      return await this.generateGeminiAudio(text);
    }
    return null;
  }
  stop() {
    if ("speechSynthesis" in window) {
      window.speechSynthesis.cancel();
    }
    if (this.currentAudio) {
      this.currentAudio.pause();
      this.currentAudio = null;
    }
  }
  speakWithWebSpeech(text) {
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = this.settings.language || "ko-KR";
    utterance.rate = 1;
    const voices = speechSynthesis.getVoices();
    const voice = voices.find((v) => v.lang.startsWith(this.settings.language.substring(0, 2)));
    if (voice)
      utterance.voice = voice;
    window.speechSynthesis.speak(utterance);
  }
  async generateOpenAIAudio(text) {
    if (!this.settings.openaiApiKey) {
      new import_obsidian4.Notice("OpenAI API Key\uAC00 \uC124\uC815\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.");
      return null;
    }
    try {
      const response = await (0, import_obsidian4.requestUrl)({
        url: "https://api.openai.com/v1/audio/speech",
        method: "POST",
        headers: {
          "Authorization": `Bearer ${this.settings.openaiApiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: "tts-1",
          input: text,
          voice: this.settings.voiceId || "nova",
          response_format: "mp3"
        })
      });
      if (response.status !== 200)
        throw new Error(`OpenAI TTS Error: ${response.status}`);
      return response.arrayBuffer;
    } catch (error) {
      console.error("[DevotionalVoice] OpenAI TTS failed:", error);
      new import_obsidian4.Notice(`OpenAI TTS \uC2E4\uD328: ${error.message}`);
      return null;
    }
  }
  async generateGeminiAudio(text) {
    var _a, _b, _c, _d, _e;
    if (!this.settings.googleApiKey) {
      new import_obsidian4.Notice("Gemini API Key\uAC00 \uC124\uC815\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4.");
      return null;
    }
    try {
      let model = this.settings.geminiModel || "gemini-2.5-flash-preview-tts";
      if (model.startsWith("models/"))
        model = model.replace("models/", "");
      const voiceName = this.settings.voiceId || "Kore";
      const response = await (0, import_obsidian4.requestUrl)({
        url: `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.settings.googleApiKey}`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text }] }],
          generationConfig: {
            responseModalities: ["AUDIO"],
            speechConfig: {
              voiceConfig: {
                prebuiltVoiceConfig: { voiceName }
              }
            }
          }
        })
      });
      if (response.status !== 200) {
        console.error("[DevotionalVoice] Gemini API Error:", response.text);
        throw new Error(`Gemini API Error: ${response.status}`);
      }
      const data = response.json;
      if (!((_c = (_b = (_a = data.candidates) == null ? void 0 : _a[0]) == null ? void 0 : _b.content) == null ? void 0 : _c.parts)) {
        throw new Error("Invalid Gemini response format");
      }
      const parts = data.candidates[0].content.parts;
      for (const part of parts) {
        if ((_e = (_d = part.inlineData) == null ? void 0 : _d.mimeType) == null ? void 0 : _e.startsWith("audio/")) {
          const base64Data = part.inlineData.data;
          const mimeType = part.inlineData.mimeType;
          const binaryString = window.atob(base64Data);
          const rawBytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            rawBytes[i] = binaryString.charCodeAt(i);
          }
          const wavBuffer = this.convertToWav(rawBytes, mimeType);
          return wavBuffer;
        }
      }
      new import_obsidian4.Notice("Gemini TTS: \uC624\uB514\uC624 \uB370\uC774\uD130\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return null;
    } catch (error) {
      console.error("[DevotionalVoice] Gemini TTS failed:", error);
      new import_obsidian4.Notice(`Gemini TTS \uC2E4\uD328: ${error.message}`);
      return null;
    }
  }
  /**
   * Convert raw PCM audio data to WAV format
   */
  convertToWav(audioData, mimeType) {
    const params = this.parseAudioMimeType(mimeType);
    const bitsPerSample = params.bitsPerSample;
    const sampleRate = params.rate;
    const numChannels = 1;
    const dataSize = audioData.length;
    const bytesPerSample = bitsPerSample / 8;
    const blockAlign = numChannels * bytesPerSample;
    const byteRate = sampleRate * blockAlign;
    const chunkSize = 36 + dataSize;
    const header = new ArrayBuffer(44);
    const view = new DataView(header);
    this.writeString(view, 0, "RIFF");
    view.setUint32(4, chunkSize, true);
    this.writeString(view, 8, "WAVE");
    this.writeString(view, 12, "fmt ");
    view.setUint32(16, 16, true);
    view.setUint16(20, 1, true);
    view.setUint16(22, numChannels, true);
    view.setUint32(24, sampleRate, true);
    view.setUint32(28, byteRate, true);
    view.setUint16(32, blockAlign, true);
    view.setUint16(34, bitsPerSample, true);
    this.writeString(view, 36, "data");
    view.setUint32(40, dataSize, true);
    const wavBuffer = new ArrayBuffer(44 + dataSize);
    const wavView = new Uint8Array(wavBuffer);
    wavView.set(new Uint8Array(header), 0);
    wavView.set(audioData, 44);
    return wavBuffer;
  }
  writeString(view, offset, str) {
    for (let i = 0; i < str.length; i++) {
      view.setUint8(offset + i, str.charCodeAt(i));
    }
  }
  parseAudioMimeType(mimeType) {
    let bitsPerSample = 16;
    let rate = 24e3;
    const parts = mimeType.split(";");
    for (const param of parts) {
      const trimmed = param.trim();
      if (trimmed.toLowerCase().startsWith("rate=")) {
        try {
          rate = parseInt(trimmed.split("=")[1], 10);
        } catch (e) {
        }
      } else if (trimmed.startsWith("audio/L")) {
        try {
          bitsPerSample = parseInt(trimmed.split("L")[1], 10);
        } catch (e) {
        }
      }
    }
    return { bitsPerSample, rate };
  }
  async playAudioBuffer(arrayBuffer) {
    try {
      const blob = new Blob([arrayBuffer], { type: "audio/wav" });
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      this.currentAudio = audio;
      audio.onended = () => {
        URL.revokeObjectURL(url);
        this.currentAudio = null;
      };
      audio.onerror = (e) => {
        console.error("[DevotionalVoice] Audio playback error:", e);
        new import_obsidian4.Notice("\uC624\uB514\uC624 \uC7AC\uC0DD \uC2E4\uD328");
        URL.revokeObjectURL(url);
        this.currentAudio = null;
      };
      await audio.play();
    } catch (e) {
      console.error("[DevotionalVoice] Audio playback failed:", e);
      new import_obsidian4.Notice("\uC624\uB514\uC624 \uC7AC\uC0DD \uC2E4\uD328");
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
};

// src/modals.ts
var import_obsidian5 = require("obsidian");
var RecordingModal = class extends import_obsidian5.Modal {
  constructor(app, recorder, onStop) {
    super(app);
    this.recorder = recorder;
    this.onStop = onStop;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("voice-writing-recording-modal");
    const container = contentEl.createDiv({ cls: "recording-container" });
    const canvas = container.createEl("canvas", { cls: "recording-visualizer" });
    canvas.width = 300;
    canvas.height = 100;
    this.canvasCtx = canvas.getContext("2d");
    const stream = this.recorder.getStream();
    if (stream) {
      this.audioContext = new (window.AudioContext || window.webkitAudioContext)();
      const source = this.audioContext.createMediaStreamSource(stream);
      this.analyser = this.audioContext.createAnalyser();
      this.analyser.fftSize = 256;
      source.connect(this.analyser);
      this.dataArray = new Uint8Array(this.analyser.frequencyBinCount);
      this.drawVisualizer();
    }
    container.createEl("h2", { text: "Recording in Progress..." });
    this.timerEl = container.createDiv({ cls: "recording-timer", text: "00:00" });
    this.startTime = Date.now();
    this.timerInterval = window.setInterval(() => this.updateTimer(), 1e3);
    const btnContainer = container.createDiv({ cls: "recording-controls" });
    const stopBtn = btnContainer.createEl("button", {
      text: "Stop Recording",
      cls: "mod-cta stop-recording-btn"
    });
    stopBtn.onclick = () => {
      this.onStop();
      this.close();
    };
  }
  drawVisualizer() {
    if (!this.analyser)
      return;
    this.animationId = requestAnimationFrame(() => this.drawVisualizer());
    this.analyser.getByteFrequencyData(this.dataArray);
    const canvas = this.canvasCtx.canvas;
    const width = canvas.width;
    const height = canvas.height;
    const ctx = this.canvasCtx;
    ctx.clearRect(0, 0, width, height);
    const barWidth = width / this.dataArray.length * 2.5;
    let barHeight;
    let x = 0;
    for (let i = 0; i < this.dataArray.length; i++) {
      barHeight = this.dataArray[i] / 2;
      const r = barHeight + 25 * (i / this.dataArray.length);
      const g = 250 * (i / this.dataArray.length);
      const b = 50;
      ctx.fillStyle = `rgb(${r},${g},${b})`;
      ctx.fillRect(x, height - barHeight, barWidth, barHeight);
      x += barWidth + 1;
    }
  }
  updateTimer() {
    if (!this.timerEl)
      return;
    const diff = Math.floor((Date.now() - this.startTime) / 1e3);
    const mins = Math.floor(diff / 60).toString().padStart(2, "0");
    const secs = (diff % 60).toString().padStart(2, "0");
    this.timerEl.setText(`${mins}:${secs}`);
  }
  onClose() {
    if (this.timerInterval)
      clearInterval(this.timerInterval);
    if (this.animationId)
      cancelAnimationFrame(this.animationId);
    if (this.audioContext && this.audioContext.state !== "closed") {
      this.audioContext.close().catch((e) => console.error("[DevotionalVoice] Error shutting down AudioContext:", e));
    }
    this.contentEl.empty();
  }
};
var ProcessingModal = class extends import_obsidian5.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("voice-writing-processing-modal");
    const container = contentEl.createDiv({ cls: "processing-container" });
    container.createEl("h2", { text: "\u2728 Generating Devotional..." });
    this.contentContainer = container.createDiv({ cls: "streaming-content-container" });
    this.contentContainer.style.maxHeight = "400px";
    this.contentContainer.style.overflowY = "auto";
    this.contentContainer.style.padding = "10px";
    this.contentContainer.style.backgroundColor = "var(--background-secondary)";
    this.contentContainer.style.borderRadius = "5px";
    this.contentContainer.style.whiteSpace = "pre-wrap";
    this.streamingTextEl = this.contentContainer.createDiv({ cls: "streaming-text" });
    const hint = container.createEl("small", { text: "Streaming from Gemini...", cls: "processing-hint" });
  }
  appendContent(text) {
    if (this.streamingTextEl) {
      this.streamingTextEl.setText(this.streamingTextEl.getText() + text);
      this.contentContainer.scrollTop = this.contentContainer.scrollHeight;
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var DEFAULT_PROMPT_HINT = `\uB2F9\uC2E0\uC740 \uD0C1\uC6D4\uD55C \uC601\uC131\uC744 \uC9C0\uB2CC \uC2E0\uD559\uC790\uC774\uC790, \uCCAD\uC911\uC758 \uB9C8\uC74C\uC744 \uC704\uB85C\uD558\uB294 \uC124\uAD50\uC790\uC785\uB2C8\uB2E4.
\uC0AC\uC6A9\uC790\uC758 \uBB35\uC0C1 \uB0B4\uC6A9\uACFC \uAD00\uB828 \uB178\uD2B8\uB97C \uBC14\uD0D5\uC73C\uB85C, \uAE4A\uC774 \uC788\uB294 \uC2E0\uD559\uC801 \uD1B5\uCC30\uACFC \uB530\uB73B\uD55C \uBAA9\uD68C\uC801 \uC801\uC6A9\uC774 \uB2F4\uAE34 \uBB35\uC0C1\uAE00\uC744 \uC791\uC131\uD574 \uC8FC\uC138\uC694.
\uBC18\uB4DC\uC2DC JSON \uD615\uC2DD({"markdown":"...", "ttsScript":"..."})\uC73C\uB85C \uCD9C\uB825.

\uC5B8\uC5B4: \uD55C\uAD6D\uC5B4`;
var DEFAULT_SETTINGS = {
  openaiApiKey: "",
  groqApiKey: "",
  language: "ko",
  serviceProvider: "groq",
  whitelistFolders: "",
  ragMaxResults: 5,
  geminiApiKey: "",
  geminiModel: "gemini-2.0-flash",
  prompts: [
    { name: "\uAE30\uBCF8 \uD15C\uD50C\uB9BF", content: DEFAULT_PROMPT_HINT }
  ],
  activePromptIndex: 0,
  ttsEnabled: true,
  ttsProvider: "gemini",
  // Default to gemini
  ttsOpenAiVoice: "nova",
  ttsGeminiModel: "gemini-2.5-flash-preview-tts",
  ttsGeminiVoice: "Kore",
  ttsLanguage: "ko-KR"
};
var DevotionalVoicePlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.recordingModal = null;
  }
  async onload() {
    console.log("[DevotionalVoice] Loading plugin...");
    await this.loadSettings();
    if (this.settings.devotionalTemplate && this.settings.devotionalTemplate.trim().length > 0) {
      console.log("[DevotionalVoice] Migrating legacy template...");
      if (this.settings.prompts.length === 1 && this.settings.prompts[0].name === "\uAE30\uBCF8 \uD15C\uD50C\uB9BF" && this.settings.prompts[0].content === DEFAULT_PROMPT_HINT) {
        this.settings.prompts[0].content = this.settings.devotionalTemplate;
        this.settings.devotionalTemplate = "";
        await this.saveSettings();
        new import_obsidian6.Notice('\uAE30\uC874 \uD15C\uD50C\uB9BF\uC774 "\uAE30\uBCF8 \uD15C\uD50C\uB9BF"\uC73C\uB85C \uC548\uC804\uD558\uAC8C \uC774\uB3D9\uB418\uC5C8\uC2B5\uB2C8\uB2E4.');
      }
    }
    this.recorder = new MicrophoneRecorder();
    this.transcriptionService = new TranscriptionService();
    this.ragService = new RAGService(this.app, this.getRAGSettings());
    this.generationService = new GenerationService(this.getGenerationSettings());
    this.ttsService = new TTSService(this.getTTSSettings());
    this.ribbonIconEl = this.addRibbonIcon("book-open", "Devotional Voice", (evt) => {
      this.showInputModeSelection();
    });
    this.ribbonIconEl.addClass("devotional-voice-ribbon");
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar("Ready");
    this.addCommand({
      id: "devotional-from-voice",
      name: "From Voice: \uC74C\uC131\uC73C\uB85C \uBB35\uC0C1 \uC2DC\uC791",
      callback: () => this.startVoiceDevotional()
    });
    this.addCommand({
      id: "devotional-from-selection",
      name: "From Selection: \uC120\uD0DD \uD14D\uC2A4\uD2B8\uB85C \uBB35\uC0C1",
      editorCallback: (editor) => this.startSelectionDevotional(editor)
    });
    this.addCommand({
      id: "devotional-from-note",
      name: "From Current Note: \uD604\uC7AC \uB178\uD2B8\uB85C \uBB35\uC0C1",
      callback: () => this.startNoteDevotional()
    });
    this.addCommand({
      id: "devotional-read-aloud",
      name: "Read Aloud: TTS \uC7AC\uC0DD",
      editorCallback: (editor) => this.readAloud(editor)
    });
    this.addCommand({
      id: "devotional-stop-tts",
      name: "Stop TTS: \uC7AC\uC0DD \uC911\uC9C0",
      callback: () => this.ttsService.stop()
    });
    this.addCommand({
      id: "devotional-save-audio",
      name: "Save Audio: TTS \uB300\uBCF8 \uC624\uB514\uC624 \uC800\uC7A5",
      editorCallback: (editor) => this.saveAudioToNote(editor)
    });
    this.addCommand({
      id: "devotional-generate-tts-only",
      name: "Generate TTS Script: \uD604\uC7AC \uB178\uD2B8\uB85C\uBD80\uD130 TTS \uB300\uBCF8 \uC0DD\uC131",
      callback: () => this.generateTtsScriptFromNote()
    });
    this.addSettingTab(new DevotionalVoiceSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        const selection = editor.getSelection();
        const content = editor.getValue();
        const hasTtsScript = /%%TTS-SCRIPT:(.*?)%%/s.test(content);
        menu.addSeparator();
        menu.addItem((item) => {
          item.setTitle("\u{1F3A4} \uC74C\uC131\uC73C\uB85C \uBB35\uC0C1 \uC2DC\uC791").setIcon("microphone").onClick(async () => {
            await this.startVoiceDevotional();
          });
        });
        if (selection && selection.trim().length > 0) {
          menu.addItem((item) => {
            item.setTitle("\u{1F4DD} \uC120\uD0DD \uD14D\uC2A4\uD2B8\uB85C \uBB35\uC0C1").setIcon("highlighter").onClick(async () => {
              await this.startSelectionDevotional(editor);
            });
          });
        }
        menu.addItem((item) => {
          item.setTitle("\u{1F4C2} \uD604\uC7AC \uB178\uD2B8\uB85C \uBB35\uC0C1 \uC2DC\uC791").setIcon("file-text").onClick(async () => {
            await this.startNoteDevotional();
          });
        });
        menu.addItem((item) => {
          item.setTitle("\u{1F399}\uFE0F \uD604\uC7AC \uB178\uD2B8\uC5D0\uC11C TTS \uB300\uBCF8\uB9CC \uC0DD\uC131").setIcon("speech").onClick(async () => {
            await this.generateTtsScriptFromNote();
          });
        });
        if (hasTtsScript) {
          menu.addItem((item) => {
            item.setTitle("\u{1F4BE} TTS \uB300\uBCF8 \uC624\uB514\uC624 \uC800\uC7A5").setIcon("save").onClick(async () => {
              await this.saveAudioToNote(editor);
            });
          });
        }
        menu.addSeparator();
      })
    );
    console.log("[DevotionalVoice] Plugin loaded successfully.");
  }
  getRAGSettings() {
    return {
      whitelistFolders: this.settings.whitelistFolders.split(",").map((f) => f.trim()).filter((f) => f.length > 0),
      maxResults: this.settings.ragMaxResults,
      geminiApiKey: this.settings.geminiApiKey,
      geminiModel: this.settings.geminiModel
    };
  }
  getGenerationSettings() {
    if (this.settings.activePromptIndex < 0 || this.settings.activePromptIndex >= this.settings.prompts.length) {
      this.settings.activePromptIndex = 0;
    }
    return {
      geminiApiKey: this.settings.geminiApiKey,
      geminiModel: this.settings.geminiModel,
      devotionalTemplate: this.settings.prompts[this.settings.activePromptIndex].content
    };
  }
  getTTSSettings() {
    return {
      provider: this.settings.ttsProvider,
      googleApiKey: this.settings.geminiApiKey,
      openaiApiKey: this.settings.openaiApiKey,
      elevenlabsApiKey: "",
      voiceId: this.settings.ttsProvider === "openai" ? this.settings.ttsOpenAiVoice : this.settings.ttsGeminiVoice,
      geminiModel: this.settings.ttsGeminiModel,
      language: this.settings.ttsLanguage
    };
  }
  showInputModeSelection() {
    new InputModeModal(this.app, (mode) => {
      switch (mode) {
        case "voice":
          this.startVoiceDevotional();
          break;
        case "selection":
          const view = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
          if (view) {
            this.startSelectionDevotional(view.editor);
          } else {
            new import_obsidian6.Notice("\uD14D\uC2A4\uD2B8\uB97C \uC120\uD0DD\uD560 \uC218 \uC788\uB294 \uB178\uD2B8\uB97C \uC5F4\uC5B4\uC8FC\uC138\uC694.");
          }
          break;
        case "note":
          this.startNoteDevotional();
          break;
        case "tts_only":
          this.generateTtsScriptFromNote();
          break;
      }
    }).open();
  }
  async startVoiceDevotional() {
    try {
      await this.recorder.startRecording();
      new import_obsidian6.Notice("\u{1F3A4} \uB179\uC74C \uC2DC\uC791...");
      this.updateStatusBar("Recording...");
      this.recordingModal = new RecordingModal(this.app, this.recorder, () => this.stopVoiceRecording());
      this.recordingModal.open();
    } catch (error) {
      console.error("[DevotionalVoice] startVoiceDevotional error:", error);
      new import_obsidian6.Notice((error == null ? void 0 : error.message) || ERROR_MESSAGES.MICROPHONE_GENERAL_ERROR);
    }
  }
  async stopVoiceRecording() {
    if (this.recordingModal) {
      this.recordingModal.close();
      this.recordingModal = null;
    }
    try {
      const blob = await this.recorder.stopRecording();
      this.updateStatusBar("Transcribing...");
      new import_obsidian6.Notice("\u{1F4DD} \uC74C\uC131 \uBCC0\uD658 \uC911...");
      const apiKey = this.settings.serviceProvider === "openai" ? this.settings.openaiApiKey : this.settings.groqApiKey;
      const result = await this.transcriptionService.transcribe(blob, apiKey, this.settings.language, this.settings.serviceProvider);
      await this.processDevotional(result.text);
    } catch (error) {
      console.error("[DevotionalVoice] stopVoiceRecording error:", error);
      new import_obsidian6.Notice("\uC74C\uC131 \uBCC0\uD658 \uC2E4\uD328");
      this.updateStatusBar("Error");
    }
  }
  async startSelectionDevotional(editor) {
    const selectedText = editor.getSelection();
    if (!selectedText || selectedText.trim().length === 0) {
      new import_obsidian6.Notice("\uBB35\uC0C1\uD560 \uD14D\uC2A4\uD2B8\uB97C \uC120\uD0DD\uD574\uC8FC\uC138\uC694.");
      return;
    }
    await this.processDevotional(selectedText);
  }
  async startNoteDevotional() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian6.Notice("\uC5F4\uB9B0 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    const content = await this.app.vault.read(activeFile);
    if (!content || content.trim().length === 0) {
      new import_obsidian6.Notice("\uB178\uD2B8\uAC00 \uBE44\uC5B4\uC788\uC2B5\uB2C8\uB2E4.");
      return;
    }
    await this.processDevotional(content);
  }
  async generateTtsScriptFromNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian6.Notice("\uC5F4\uB9B0 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    const content = await this.app.vault.read(activeFile);
    if (!content || content.trim().length === 0) {
      new import_obsidian6.Notice("\uB178\uD2B8\uAC00 \uBE44\uC5B4\uC788\uC2B5\uB2C8\uB2E4.");
      return;
    }
    console.log("[DevotionalVoice] generateTtsScriptFromNote started.");
    this.updateStatusBar("Generating TTS...");
    const processingModal = new ProcessingModal(this.app);
    processingModal.open();
    processingModal.appendContent(`### \u{1F399}\uFE0F \uD604\uC7AC \uB178\uD2B8\uB85C\uBD80\uD130 TTS \uB300\uBCF8 \uC0DD\uC131 \uC911...

`);
    try {
      const generator = this.generationService.streamGenerateTts(content);
      let fullText = "";
      for await (const chunk of generator) {
        fullText += chunk;
        processingModal.appendContent(chunk);
      }
      processingModal.close();
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (activeView) {
        const editor = activeView.editor;
        const ttsBlock = `

%%TTS-SCRIPT:${fullText.trim()}%%`;
        const lineCount = editor.lineCount();
        editor.replaceRange(ttsBlock, { line: lineCount, ch: 0 });
        new import_obsidian6.Notice("\u2705 TTS \uB300\uBCF8\uC774 \uB178\uD2B8 \uD558\uB2E8\uC5D0 \uAE30\uB85D\uB418\uC5C8\uC2B5\uB2C8\uB2E4.");
        this.updateStatusBar("Ready");
      }
    } catch (e) {
      if (processingModal)
        try {
          processingModal.close();
        } catch (e2) {
        }
      console.error("[DevotionalVoice] TTS Generation Failed:", e);
      new import_obsidian6.Notice("TTS \uB300\uBCF8 \uC0DD\uC131 \uC2E4\uD328: " + e.message);
      this.updateStatusBar("Error");
    }
  }
  async processDevotional(userInput) {
    console.log("[DevotionalVoice] processDevotional started.");
    this.updateStatusBar("Processing...");
    const processingModal = new ProcessingModal(this.app);
    processingModal.open();
    let ragResults = [];
    try {
      new import_obsidian6.Notice("\u{1F50D} \uAD00\uB828 \uB178\uD2B8 \uAC80\uC0C9 \uC911...");
      ragResults = await this.ragService.search(userInput, this.settings.ragMaxResults);
      console.log(`[DevotionalVoice] RAG found ${ragResults.length} results.`);
      processingModal.appendContent(`

[System] Found ${ragResults.length} relevant notes.

`);
      new import_obsidian6.Notice("\u2728 \uBB35\uC0C1\uAE00 \uC0DD\uC131 \uC911 (Streaming)...");
      console.log("[DevotionalVoice] Starting Gemini Stream Generation...");
      const generator = this.generationService.streamGenerate(userInput, ragResults);
      let fullText = "";
      for await (const chunk of generator) {
        fullText += chunk;
        processingModal.appendContent(chunk);
      }
      const parsedResult = this.generationService.parseResponse(fullText);
      const devotionalText = parsedResult.markdown;
      const ttsScript = parsedResult.ttsScript;
      processingModal.close();
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (activeView) {
        const editor = activeView.editor;
        const timestamp = new Date().toLocaleString("ko-KR");
        let referenceSection = "\n\n### \u{1F4DA} \uCC38\uC870 \uB178\uD2B8\n";
        if (ragResults.length > 0) {
          referenceSection += ragResults.map((r) => `- [[${r.file.basename}]]`).join("\n");
        } else {
          referenceSection += "- \uCC38\uC870\uD55C \uAE30\uC874 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.";
        }
        const ttsBlock = ttsScript ? `

%%TTS-SCRIPT:${ttsScript}%%` : "";
        const insertionText = `

---
## \u2728 AI \uBB35\uC0C1 \uACB0\uACFC (${timestamp})

${devotionalText}
${referenceSection}${ttsBlock}

---`;
        const cursor = editor.getCursor();
        editor.replaceRange(insertionText, cursor);
        new import_obsidian6.Notice("\u2705 \uBB35\uC0C1\uAE00\uC774 \uB178\uD2B8\uC5D0 \uAE30\uB85D\uB418\uC5C8\uC2B5\uB2C8\uB2E4.");
        this.updateStatusBar("Ready");
      } else {
        new import_obsidian6.Notice("\uBB35\uC0C1 \uACB0\uACFC\uB97C \uAE30\uB85D\uD560 \uD65C\uC131 \uB178\uD2B8\uB97C \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.");
      }
    } catch (e) {
      if (processingModal)
        try {
          processingModal.close();
        } catch (e2) {
        }
      console.error("[DevotionalVoice] processDevotional error:", e);
      new import_obsidian6.Notice("\uC624\uB958 \uBC1C\uC0DD: " + (e.message || "\uC54C \uC218 \uC5C6\uB294 \uC624\uB958"));
      this.updateStatusBar("Error");
    }
  }
  async readAloud(editor) {
    const selectedText = editor.getSelection();
    if (selectedText && selectedText.trim().length > 0) {
      new import_obsidian6.Notice("\u{1F50A} \uC120\uD0DD \uD14D\uC2A4\uD2B8 \uC7AC\uC0DD \uC911...");
      await this.ttsService.speak(selectedText);
      return;
    }
    const content = editor.getValue();
    const ttsMatch = content.match(/%%TTS-SCRIPT:(.*?)%%/s);
    if (ttsMatch && ttsMatch[1]) {
      new import_obsidian6.Notice("\u{1F50A} \uBB35\uC0C1 \uB300\uBCF8 \uC7AC\uC0DD \uC911...");
      await this.ttsService.speak(ttsMatch[1].trim());
      return;
    }
    new import_obsidian6.Notice("\uC77D\uC744 \uD14D\uC2A4\uD2B8\uB97C \uC120\uD0DD\uD558\uAC70\uB098 \uC0DD\uC131\uB41C \uBB35\uC0C1\uAE00\uC774 \uD544\uC694\uD569\uB2C8\uB2E4.");
  }
  /**
   * Save TTS audio file to the same folder as the active note
   * Converts to MP3 if ffmpeg is available
   */
  async saveAudioToNote(editor) {
    const content = editor.getValue();
    const ttsMatch = content.match(/%%TTS-SCRIPT:(.*?)%%/s);
    if (!ttsMatch || !ttsMatch[1]) {
      new import_obsidian6.Notice("TTS \uB300\uBCF8\uC774 \uC5C6\uC2B5\uB2C8\uB2E4. \uBB35\uC0C1\uAE00\uC744 \uBA3C\uC800 \uC0DD\uC131\uD574\uC8FC\uC138\uC694.");
      return;
    }
    const ttsScript = ttsMatch[1].trim();
    new import_obsidian6.Notice("\u{1F50A} \uC624\uB514\uC624 \uD30C\uC77C \uC0DD\uC131 \uC911...");
    const audioBuffer = await this.ttsService.generateAudio(ttsScript);
    if (!audioBuffer) {
      new import_obsidian6.Notice("\uC624\uB514\uC624 \uC0DD\uC131 \uC2E4\uD328");
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    let folderPath = "";
    if (activeFile && activeFile.parent) {
      folderPath = activeFile.parent.path;
    }
    const timestamp = (0, import_obsidian6.moment)().format("YYYYMMDD_HHmmss");
    const wavFileName = `Devotional_Audio_${timestamp}.wav`;
    const wavFilePath = folderPath ? `${folderPath}/${wavFileName}` : wavFileName;
    const mp3FileName = `Devotional_Audio_${timestamp}.mp3`;
    const wavFile = await this.app.vault.createBinary(wavFilePath, audioBuffer);
    let finalFileName = wavFileName;
    try {
      const basePath = this.app.vault.adapter.basePath;
      if (basePath) {
        const { exec } = require("child_process");
        const path = require("path");
        const inputAbsPath = path.join(basePath, wavFilePath);
        const outputAbsPath = inputAbsPath.replace(".wav", ".mp3");
        new import_obsidian6.Notice("\u{1F504} MP3 \uBCC0\uD658 \uC911...");
        await new Promise((resolve, reject) => {
          exec(`ffmpeg -y -i "${inputAbsPath}" -codec:a libmp3lame -qscale:a 2 "${outputAbsPath}"`, (error) => {
            if (error)
              reject(error);
            else
              resolve();
          });
        });
        await this.app.vault.delete(wavFile);
        finalFileName = mp3FileName;
        new import_obsidian6.Notice(`\u{1F4BE} \uC624\uB514\uC624 \uC800\uC7A5 \uC644\uB8CC: ${finalFileName}`);
      } else {
        new import_obsidian6.Notice(`\u{1F4BE} \uC624\uB514\uC624 \uC800\uC7A5 \uC644\uB8CC (WAV): ${finalFileName}`);
      }
    } catch (e) {
      console.error("[DevotionalVoice] MP3 Conversion failed:", e);
      new import_obsidian6.Notice("MP3 \uBCC0\uD658 \uC2E4\uD328. WAV\uB85C \uC800\uC7A5\uB429\uB2C8\uB2E4.");
      finalFileName = wavFileName;
    }
    const audioEmbed = `

![[${finalFileName}]]`;
    const cursor = editor.getCursor("to");
    editor.replaceRange(audioEmbed, { line: cursor.line + 1, ch: 0 });
  }
  updateStatusBar(text) {
    this.statusBarItem.setText(`\u{1F4D6} ${text}`);
  }
  onunload() {
    this.ttsService.stop();
    console.log("[DevotionalVoice] Plugin unloaded.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.ragService.updateSettings(this.getRAGSettings());
    this.generationService.updateSettings(this.getGenerationSettings());
    this.ttsService.updateSettings(this.getTTSSettings());
  }
};
var InputModeModal = class extends import_obsidian6.Modal {
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("devotional-input-modal");
    contentEl.createEl("h2", { text: "\u{1F4D6} \uBB35\uC0C1 \uC785\uB825 \uBC29\uC2DD \uC120\uD0DD" });
    const buttonContainer = contentEl.createDiv({ cls: "input-mode-buttons" });
    const voiceBtn = buttonContainer.createEl("button", { text: "\u{1F3A4} \uC74C\uC131 \uB179\uC74C", cls: "mod-cta" });
    voiceBtn.onclick = () => {
      this.close();
      this.onSelect("voice");
    };
    const selectionBtn = buttonContainer.createEl("button", { text: "\u{1F4DD} \uD14D\uC2A4\uD2B8 \uC120\uD0DD" });
    selectionBtn.onclick = () => {
      this.close();
      this.onSelect("selection");
    };
    const noteBtn = buttonContainer.createEl("button", { text: "\u{1F4C2} \uD604\uC7AC \uB178\uD2B8\uB85C \uBB35\uC0C1" });
    noteBtn.onclick = () => {
      this.close();
      this.onSelect("note");
    };
    const ttsOnlyBtn = buttonContainer.createEl("button", { text: "\u{1F399}\uFE0F TTS \uB300\uBCF8\uB9CC \uC0DD\uC131" });
    ttsOnlyBtn.onclick = () => {
      this.close();
      this.onSelect("tts_only");
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DevotionalVoiceSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F4D6} Devotional Voice Settings" });
    containerEl.createEl("h3", { text: "\u{1F3A4} \uC74C\uC131 \uC778\uC2DD (STT)" });
    new import_obsidian6.Setting(containerEl).setName("Service Provider").setDesc("OpenAI \uB610\uB294 Groq").addDropdown((d) => d.addOption("openai", "OpenAI").addOption("groq", "Groq").setValue(this.plugin.settings.serviceProvider).onChange(async (v) => {
      this.plugin.settings.serviceProvider = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("OpenAI API Key").setDesc(document.createDocumentFragment()).then((s) => {
      s.descEl.createEl("a", { href: "https://platform.openai.com/api-keys", text: "Get API Key", cls: "u-popover" });
    }).addText((t) => t.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (v) => {
      this.plugin.settings.openaiApiKey = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("Groq API Key").setDesc(document.createDocumentFragment()).then((s) => {
      s.descEl.createEl("a", { href: "https://console.groq.com/keys", text: "Get API Key", cls: "u-popover" });
    }).addText((t) => t.setPlaceholder("gsk_...").setValue(this.plugin.settings.groqApiKey).onChange(async (v) => {
      this.plugin.settings.groqApiKey = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u{1F50D} RAG \uAC80\uC0C9" });
    new import_obsidian6.Setting(containerEl).setName("\uD654\uC774\uD2B8\uB9AC\uC2A4\uD2B8 \uD3F4\uB354").addText((t) => t.setPlaceholder("\uBB35\uC0C1\uC77C\uC9C0/").setValue(this.plugin.settings.whitelistFolders).onChange(async (v) => {
      this.plugin.settings.whitelistFolders = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("\uCD5C\uB300 \uAC80\uC0C9 \uACB0\uACFC").addSlider((s) => s.setLimits(1, 10, 1).setValue(this.plugin.settings.ragMaxResults).setDynamicTooltip().onChange(async (v) => {
      this.plugin.settings.ragMaxResults = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u2728 \uBB35\uC0C1\uAE00 \uC0DD\uC131" });
    new import_obsidian6.Setting(containerEl).setName("Gemini API Key").setDesc(document.createDocumentFragment()).then((s) => {
      s.descEl.createEl("a", { href: "https://aistudio.google.com/app/apikey", text: "Get API Key (Google AI Studio)", cls: "u-popover" });
    }).addText((t) => t.setPlaceholder("AIza...").setValue(this.plugin.settings.geminiApiKey).onChange(async (v) => {
      this.plugin.settings.geminiApiKey = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("Gemini Model (\uC0DD\uC131)").addText((t) => t.setPlaceholder("gemini-2.0-flash").setValue(this.plugin.settings.geminiModel).onChange(async (v) => {
      this.plugin.settings.geminiModel = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h4", { text: "\uD504\uB86C\uD504\uD2B8 \uD15C\uD50C\uB9BF \uAD00\uB9AC" });
    const templateSetting = new import_obsidian6.Setting(containerEl).setName("\uD65C\uC131 \uD15C\uD50C\uB9BF").setDesc("\uC0AC\uC6A9\uD560 \uD15C\uD50C\uB9BF\uC744 \uC120\uD0DD\uD558\uAC70\uB098 \uAD00\uB9AC\uD569\uB2C8\uB2E4.").addDropdown((d) => {
      this.plugin.settings.prompts.forEach((p, i) => d.addOption(i.toString(), p.name));
      d.setValue(this.plugin.settings.activePromptIndex.toString()).onChange(async (v) => {
        this.plugin.settings.activePromptIndex = parseInt(v);
        await this.plugin.saveSettings();
        this.display();
      });
    }).addExtraButton((b) => {
      b.setIcon("plus").setTooltip("\uC0C8 \uD15C\uD50C\uB9BF \uCD94\uAC00").onClick(async () => {
        this.plugin.settings.prompts.push({
          name: `\uC0C8 \uD15C\uD50C\uB9BF ${this.plugin.settings.prompts.length + 1}`,
          content: DEFAULT_PROMPT_HINT
        });
        this.plugin.settings.activePromptIndex = this.plugin.settings.prompts.length - 1;
        await this.plugin.saveSettings();
        this.display();
      });
    }).addExtraButton((b) => {
      b.setIcon("trash").setTooltip("\uD604\uC7AC \uD15C\uD50C\uB9BF \uC0AD\uC81C").onClick(async () => {
        if (this.plugin.settings.prompts.length <= 1) {
          new import_obsidian6.Notice("\uCD5C\uC18C \uD558\uB098\uC758 \uD15C\uD50C\uB9BF\uC740 \uC720\uC9C0\uD574\uC57C \uD569\uB2C8\uB2E4.");
          return;
        }
        const idx = this.plugin.settings.activePromptIndex;
        this.plugin.settings.prompts.splice(idx, 1);
        this.plugin.settings.activePromptIndex = Math.max(0, idx - 1);
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const activePrompt = this.plugin.settings.prompts[this.plugin.settings.activePromptIndex];
    new import_obsidian6.Setting(containerEl).setName("\uD15C\uD50C\uB9BF \uC774\uB984").addText((t) => t.setValue(activePrompt.name).onChange(async (v) => {
      activePrompt.name = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("\uD504\uB86C\uD504\uD2B8 \uB0B4\uC6A9").setDesc('JSON \uCD9C\uB825 \uD615\uC2DD({"markdown":"...", "ttsScript":"..."})\uC744 \uC720\uC9C0\uD574\uC8FC\uC138\uC694.').addTextArea((t) => {
      t.inputEl.rows = 10;
      t.inputEl.cols = 50;
      t.setValue(activePrompt.content).onChange(async (v) => {
        activePrompt.content = v;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "\u{1F50A} TTS \uC124\uC815" });
    new import_obsidian6.Setting(containerEl).setName("TTS \uD65C\uC131\uD654").addToggle((t) => t.setValue(this.plugin.settings.ttsEnabled).onChange(async (v) => {
      this.plugin.settings.ttsEnabled = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("TTS \uC81C\uACF5\uC790").addDropdown((d) => d.addOption("google", "Web Speech (\uBB34\uB8CC)").addOption("openai", "OpenAI TTS").addOption("gemini", "Gemini TTS").setValue(this.plugin.settings.ttsProvider).onChange(async (v) => {
      this.plugin.settings.ttsProvider = v;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.ttsProvider === "openai") {
      new import_obsidian6.Setting(containerEl).setName("OpenAI Voice").addDropdown((d) => d.addOption("alloy", "Alloy").addOption("echo", "Echo").addOption("nova", "Nova").addOption("shimmer", "Shimmer").setValue(this.plugin.settings.ttsOpenAiVoice).onChange(async (v) => {
        this.plugin.settings.ttsOpenAiVoice = v;
        await this.plugin.saveSettings();
      }));
    } else if (this.plugin.settings.ttsProvider === "gemini") {
      new import_obsidian6.Setting(containerEl).setName("Gemini TTS Model").addText((t) => t.setPlaceholder("gemini-2.5-flash-preview-tts").setValue(this.plugin.settings.ttsGeminiModel).onChange(async (v) => {
        this.plugin.settings.ttsGeminiModel = v;
        await this.plugin.saveSettings();
      }));
      new import_obsidian6.Setting(containerEl).setName("Gemini Voice").setDesc("30\uAC00\uC9C0 \uC911 \uC8FC\uC694 15\uAC00\uC9C0").addDropdown((d) => d.addOption("Puck", "Puck (Upbeat)").addOption("Charon", "Charon (Informative)").addOption("Kore", "Kore (Firm, \uC5EC\uC131)").addOption("Fenrir", "Fenrir (Excitable, \uB0A8\uC131)").addOption("Aoede", "Aoede (Breezy)").addOption("Zephyr", "Zephyr (Bright)").addOption("Leda", "Leda (Youthful)").addOption("Orus", "Orus (Firm)").addOption("Callirrhoe", "Callirrhoe (Easy-going)").addOption("Autonoe", "Autonoe (Bright)").addOption("Enceladus", "Enceladus (Breathy)").addOption("Iapetus", "Iapetus (Clear)").addOption("Umbriel", "Umbriel (Easy-going)").addOption("Algieba", "Algieba (Smooth)").addOption("Despina", "Despina (Smooth)").setValue(this.plugin.settings.ttsGeminiVoice).onChange(async (v) => {
        this.plugin.settings.ttsGeminiVoice = v;
        await this.plugin.saveSettings();
      }));
    } else {
      new import_obsidian6.Setting(containerEl).setName("TTS \uC5B8\uC5B4").addDropdown((d) => d.addOption("ko-KR", "\uD55C\uAD6D\uC5B4").addOption("en-US", "English").setValue(this.plugin.settings.ttsLanguage).onChange(async (v) => {
        this.plugin.settings.ttsLanguage = v;
        await this.plugin.saveSettings();
      }));
    }
  }
};
